# Numpy

* NumPy is an open-source Python library that facilitates efficient numerical operations on large quantities of data.
* it uses the library called matplotlib
* one dimension array is referred to the vector
* two dimension array is referred to the matrix
* three dimension array is referred to the tensor

In [9]:
!pip install numpy

In [10]:
import numpy as np
a = [1,2,3]
a


[1, 2, 3]

## creating numpy array (one dimensional)

### 1st method

In [11]:
import numpy as np
a = [1,2,3,5]
my_arr = np.array(a)
my_arr

array([1, 2, 3, 5])

### 2nd method

In [12]:
import numpy as np
my_arr = np.array([1,2,3,5])
my_arr

array([1, 2, 3, 5])

## creating one dimensional array using Numpy

In [14]:
import numpy as np
a = []
n = int(input("write the size of the array:"))
for i in range(n):
    val =   int(input("enter the numbers:"))
    a.append(val)
my_array = np.array(a)
my_array    






array([5, 8])

## creating two dimension array
* it is known by the two lists 

In [20]:
import numpy as np
a = [[1,2,3] , [2,3,4]]
arr = np.array(a)
print(arr)
print("dimensions of array is " , arr.ndim)
print("shape of the array" , arr.shape)


[[1 2 3]
 [2 3 4]]
dimensions of array is  2
shape of the array (2, 3)


# Numpy functions

In [21]:
import numpy as np
arr = np.zeros(7)
arr

array([0., 0., 0., 0., 0., 0., 0.])

In [23]:
import numpy as np
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [25]:
import numpy as np
arr = np.ones((2 , 5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### eye()

In [29]:
import numpy as np
arr = np.eye(5)
arr


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
import numpy as np
arr = np.eye(5 , 4)  # 5 is the row and 4 is the column
arr


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

### diag()

In [34]:
import numpy as np
arr = np.diag([1,2,3,4])
print(arr)
np.diag(arr)  # we can also find out what elements are present in the array 

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


array([1, 2, 3, 4])

### randint()
* use to generate random numbers
   * syntax :
       - randint(min_value , max_value , total_values)

In [41]:
import numpy as np

arr = np.random.randint(1,9,5)
arr


array([8, 3, 3, 1, 5])

## rand() 
 * use to generate random numbers between 0 and 1
 

In [43]:
import numpy as np

arr = np.random.rand(4)
arr


array([0.13838269, 0.65696283, 0.32009623, 0.33761569])

In [44]:
import numpy as np

arr = np.random.rand(4 ,2)
arr


array([[0.5736904 , 0.70016961],
       [0.67980899, 0.71255887],
       [0.46906338, 0.8744082 ],
       [0.41265101, 0.03333817]])

## randn()
 * use to generate random value close to the 0

In [45]:
import numpy as np

arr = np.random.randn(4)
arr


array([-0.74021279,  0.63029101, -1.31479413, -0.63190679])

# indexing and slicing of array

In [48]:
import numpy as np
a = []
size = int(input("how many numbers ?"))
for i in range(size):
    a.append(int(input("enter number ")))
arr = np.array(a)    
for i in range(arr.size):
    print(arr[i])
sum = 0
total_sum = arr.sum()
print("sum of all numbers is ",total_sum)




4
5
6
sum of all numbers is  15


In [52]:
import numpy as np
a = []
size = int(input("how many numbers ?"))
for i in range(size):
    a.append(int(input("enter number ")))
arr = np.array(a)    
for i in range(arr.size):
    print(arr[i])
arr1 = arr[0:3]
print(arr1)





1
2
3
4
5
[1 2 3]


## reshaping data

### converting one dimension into two dimension

In [7]:
import numpy as np
arr = np.random.randint(1,100,12)
print(arr)
arr.shape # tells us how many numbers are produced
arr = arr.reshape(4,3) # 4*3 = 12  #converts the one dimensional array into two dimensional

arr

[34 71 48 94 79  9 64 39 16 45 47 82]


array([[34, 71, 48],
       [94, 79,  9],
       [64, 39, 16],
       [45, 47, 82]])

### converting two dimension into one dimension

In [12]:
import numpy as np
arr = np.random.randint(1,100,12)

arr = arr.reshape(4,3) 
print(arr)
print(arr.reshape(12))
print(arr.ndim)


[[44 74 42]
 [10 97 18]
 [ 5 79 35]
 [80 27  8]]
[44 74 42 10 97 18  5 79 35 80 27  8]
2


In [4]:
import numpy as np
arr = np.random.randint(1,100,12)

arr = arr.reshape(-1 , 3) 
print(arr)



[[55 99 92]
 [20 56 38]
 [77  7 10]
 [13 37  9]]


# seed function
* random numbers are fixed 

In [24]:
import numpy as np
np.random.seed(1)
arr = np.random.randint(1,50,5)
arr
# arr.size


array([38, 44, 13,  9, 10])

## indexing  two dimension array

In [30]:
import numpy as np

# Initialize the matrix list
matrix = []

# Get the number of rows and columns from the user
row = int(input("Write the number of rows:\t"))
column = int(input("Write the number of columns:\t"))

for i in range(row):
    a = []  
    for j in range(column):
        val = int(input(f"Enter the number for row {i+1}, column {j+1}:\t"))
        a.append(val)
    matrix.append(a)  # Append the row to the matrix

arr = np.array(matrix)

for i in range(row):
    for j in range(column):
        print(arr[i][j], end=" ")
    print() 


2 2 
2 2 
2 2 


## slicing of 2 dimension array

In [38]:
import numpy as np
arr = np.array([[1,2,3] , [2,3,4] , [4,6,8]])
print(arr)
# print(arr[0:2])
    #     rows , columns
print(arr[0:2 , 0:2])


[[1 2 3]
 [2 3 4]
 [4 6 8]]
[[1 2]
 [2 3]]


##### more examples

In [46]:
import numpy as np

np.random.seed(111)
a  = np.random.randint(1,100,30).reshape(6,5)
a
a[2: , 0:3]


array([[58,  8, 13],
       [89, 29, 15],
       [55, 73, 38],
       [13, 46, 70]])

# view and copy
* view:
   - A view in NumPy is a new array object that looks at the same data as the original array. Modifying the view will modify the original array and vice-versa because they share the same data.
* copy
   - A copy in NumPy creates a completely new array object with a different memory location. Any modifications made to the copy will not affect the original array, and modifications to the original array will not affect the copy.

   

In [54]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
result = a[1:4]
result[:] = 0   # by default it is view
print(result)
a

[0 0 0]


array([ 1,  0,  0,  0,  5,  6,  7,  8,  9, 10])

In [55]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
result = a[1:4].copy()
result[:] = 0   # original array is not updated
print(result)
a

[0 0 0]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# conditional selection

In [65]:
import numpy as np
a = np.arange(1,16)
print(a > 2)
print(a % 2 == 0)
print(a > 5)
print([a > 10]) == 0

[False False  True  True  True  True  True  True  True  True  True  True
  True  True  True]
[False  True False  True False  True False  True False  True False  True
 False  True False]
[False False False False False  True  True  True  True  True  True  True
  True  True  True]
[array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])]


False

# operations

In [3]:
import numpy as np
a = np.arange(1,21)
a
a ** 2
a * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [79]:
import numpy as np
a = np.array([1,2,3,4]).reshape(2,2)
b = np.array([5,6,7,8]).reshape(2,2)
print(a)
print(b)
print(a+b)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]


# numpy functions

In [3]:
import numpy as np
arr = np.array([1,2,3,4])
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr)) # position of the minimum number
print(np.argmax(arr)) 
print(np.sqrt(arr))
print(np.sin(arr))
print(np.cos(arr))

1
4
0
3
[1.         1.41421356 1.73205081 2.        ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


### linspace function
* it returns the value between given range and with the same gap between numbers
* it takes three parameters: start, stop, and num
* start is the starting value of the sequence
* stop is the end value of the sequence
* num is the number of samples to generate


In [4]:
import numpy as np
arr = np.array([1,2,3,4,56,7])
np.linspace(1,3,5)

array([1. , 1.5, 2. , 2.5, 3. ])

### now use all the above functions on the two-dimensional array

In [17]:
import numpy as np
np.random.seed(133)
arr = np.random.randint(1,15,6).reshape(2,3)
print(arr)
print(arr.sum())
print(np.min(arr , 1)) # 1 is for row
print(np.max(arr , 0))  # 0 is for column
print(np.argmin(arr)) # position of the minimum number
print(np.argmax(arr)) 
print(np.sqrt(arr))
print(np.sin(arr))
print(np.cos(arr))

[[ 2  9  9]
 [ 2  7 13]]
42
[2 2]
[ 2  9 13]
0
5
[[1.41421356 3.         3.        ]
 [1.41421356 2.64575131 3.60555128]]
[[0.90929743 0.41211849 0.41211849]
 [0.90929743 0.6569866  0.42016704]]
[[-0.41614684 -0.91113026 -0.91113026]
 [-0.41614684  0.75390225  0.90744678]]


### cumsum()
*  Python numpy cumsum() function returns the cumulative sum of the elements along the given axis. 
*  It is used to calculate the cumulative sum of the elements in the array.
*  The axis parameter specifies the dimension along which the cumulative sum is calculated.


In [19]:
import numpy as np

a = np.array([1,4,7,90,5])
a.cumsum()

array([  1,   5,  12, 102, 107])

In [35]:
import numpy as np


np.random.seed(89)


arr = np.random.randint(1, 50, 10)
print("Original Array:", arr)


np.random.shuffle(arr)
print("Shuffled Array:", arr)

unique_values = np.unique(arr)
print("Unique Values in the Array:", unique_values)

print("Number of Unique Values:", unique_values.size)

print("Array after np.unique():", arr)


Original Array: [20 31  5 46 23 44 38  9 19 34]
Shuffled Array: [46 38  5 34 31 23 20 44 19  9]
Unique Values in the Array: [ 5  9 19 20 23 31 34 38 44 46]
Number of Unique Values: 10
Array after np.unique(): [46 38  5 34 31 23 20 44 19  9]


In [34]:
import numpy as np


arr = np.random.randint(1, 50, 10)
print("Original Array:", arr)


unique_values, indices, counts = np.unique(arr, return_index=True, return_counts=True)

print("Unique Values:", unique_values)
print("Indices of Unique Values:", indices)
print("Counts of Unique Values:", counts)


Original Array: [39  8 23 46 32 20 18 30 18 41]
Unique Values: [ 8 18 20 23 30 32 39 41 46]
Indices of Unique Values: [1 6 5 2 7 4 0 9 3]
Counts of Unique Values: [1 2 1 1 1 1 1 1 1]


# stacking by numpy

In [40]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a)
print(b)
print(np.hstack((a , b)))
print(np.vstack((a , b)))



[1 2 3 4]
[5 6 7 8]
[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [46]:
import numpy as np
a = np.array(np.random.randint(1,100,20)).reshape(2,10)
b = np.array(np.random.randint(1,100,20)).reshape(2,10)
print(np.hstack((a , b)))
print(np.vstack((a , b)))



[[24 78 94 34 51 69 95 93 13 53 11 65  3 24 78 49  2 47 55 16]
 [10 83 89 50 77 77 80 68 92 10 37 99 57 55 63 61 29 21 16 92]]
[[24 78 94 34 51 69 95 93 13 53]
 [10 83 89 50 77 77 80 68 92 10]
 [11 65  3 24 78 49  2 47 55 16]
 [37 99 57 55 63 61 29 21 16 92]]


# difference b/w numpy and list
## numpy
* Numpy data structures take less space
* Numpy data structures are faster
* Numpy data structures are more memory efficient
* Numpy data structures are more suitable for large data sets
* Numpy data structures are more suitable for scientific computing
* optimised functions 
## list
* list takes more space
* list is slower
* list is less memory efficient
* list is less suitable for large data sets
* list is less suitable for scientific computing



## proof

In [2]:
%%timeit
a = []
for i in range(1 , 10):
    a.append(i ** 2)

1.23 μs ± 125 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [4]:
%timeit [i **2 for i in range(1,10)]

1.25 μs ± 315 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [5]:
import numpy as np
%timeit np.arange(1,10)**2

2.31 μs ± 267 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## numpy searching arrays

In [7]:
import numpy as np
arr = np.array([1,4,4,2,3,4,5,4])
a = np.where(arr == 4)  # it will give you index number
a

(array([1, 2, 5, 7], dtype=int64),)

In [11]:
import numpy as np
arr = np.array([5,7,8,9,0])
a = np.where(arr % 2 == 0)   # / is known as division operator which performs division and % is known as modulus operator, it is used to find the remainder.
print(a)

(array([2, 4], dtype=int64),)


In [12]:
import numpy as np
arr = np.array([5,7,8,9,0])
a = np.searchsorted(arr , 6)  # provide you the index where it is placed
a

1

#### the searching can also be performed from `right to left`

In [14]:
import numpy as np
arr = np.array([5,7,8,9,0])
a = np.searchsorted(arr , 6 , side= 'left')  # provide you the index where it is placed
a

1